import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
// import vant from "vant";
import "vant/lib/index.css";
import { Button } from "vant";
// import "amfe-flexible";
// import axios from "axios";
// app.config.globalProperties.axios = axios;
const app = createApp(App);
app.use(store);
app.use(router);
// app.use(vant);
// app.use(vant.Lazyload);
app.component("ws", Button);
app.mount("#app");
